models/Empleados.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "empleados".
 *
 * @property int $id
 * @property string $nombre
 * @property int $codigo
 * @property string $lugar_nacimiento
 * @property string $fecha_nacimiento
 * @property string $direccion
 * @property string $telefono
 * @property int $id_cargo
 * @property int $id_estado
 * @property string|null $fecha_registro
 *
 * @property Cargos $cargo
 * @property Estados $estado
 */
class Empleados extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'empleados';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nombre', 'codigo', 'lugar_nacimiento', 'fecha_nacimiento', 'direccion', 'telefono', 'id_cargo', 'id_estado'], 'required'],
            [['id_cargo', 'id_estado'], 'integer'],
            [['codigo'], 'integer', 'max' => 9999, 'min' => 0],
            [['telefono'], 'match', 'pattern' => '/[0-9].{4,15}/', 'message'=>'Telefono debe ser numerico, minimo 5 a 15 caracteres.'],
            [['lugar_nacimiento'], 'match', 'pattern' => '/[A-Za-z.,-].{1,49}/', 'message'=>'Lugar de nacimiento no puede contener numeros, minimo 2 a 50 caracteres.'],
            [['fecha_nacimiento', 'fecha_registro'], 'safe'],
            [['direccion'], 'string', 'max' => 255],
            [['nombre'], 'string', 'max' => 50, 'min' => 2],
            [['codigo'], 'unique'],
            [['id_cargo'], 'exist', 'skipOnError' => true, 'targetClass' => Cargos::className(), 'targetAttribute' => ['id_cargo' => 'id']],
            [['id_estado'], 'exist', 'skipOnError' => true, 'targetClass' => Estados::className(), 'targetAttribute' => ['id_estado' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'codigo' => 'Codigo',
            'lugar_nacimiento' => 'Lugar Nacimiento',
            'fecha_nacimiento' => 'Fecha Nacimiento',
            'direccion' => 'Direccion',
            'telefono' => 'Telefono',
            'id_cargo' => 'Id Cargo',
            'id_estado' => 'Id Estado',
            'fecha_registro' => 'Fecha Registro',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCargo()
    {
        return $this->hasOne(Cargos::className(), ['id' => 'id_cargo']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEstado()
    {
        return $this->hasOne(Estados::className(), ['id' => 'id_estado']);
    }
}

controllers/CargosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Cargos;
use app\models\CargosSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CargosController implements the CRUD actions for Cargos model.
 */
class CargosController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Cargos models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CargosSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Cargos model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Cargos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Cargos();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Cargos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Cargos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Cargos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Cargos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Cargos::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/EmpleadosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Empleados;
use app\models\EmpleadosSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * EmpleadosController implements the CRUD actions for Empleados model.
 */
class EmpleadosController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Empleados models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new EmpleadosSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Empleados model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Empleados model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Empleados();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Empleados model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Empleados model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Empleados model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Empleados the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Empleados::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/EstadosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Estados;
use app\models\EstadosSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * EstadosController implements the CRUD actions for Estados model.
 */
class EstadosController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Estados models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new EstadosSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Estados model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Estados model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Estados();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Estados model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Estados model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Estados model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Estados the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Estados::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/empleados/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Cargos;
use app\models\Estados;
use yii\jui\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\Empleados */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="empleados-form">

    <?php $form = ActiveForm::begin(); ?>
    
    <div class="col-md-8 col-md-offset-2">
        <div class="row">
            
            <div class="col-md-6">
                <div class="form-group">
                    <?= $form->field($model, 'codigo')->textInput() ?>
                </div>
            </div>
        

        
            <div class="col-md-6">
                <div class="form-group">
                    <?= $form->field($model, 'nombre')->textInput() ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <?= $form->field($model, 'lugar_nacimiento')->textInput(['maxlength' => true]) ?>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                         
                <?php echo $form->field($model,'fecha_nacimiento')->
                    widget(DatePicker::className(),[
                        'dateFormat' => 'yyyy-MM-dd',
                        'clientOptions' => [
                            'yearRange' => '-115:+0',
                            'changeYear' => true
                        ],
                        'options' => ['class' => 'form-control']
                    ]) 
                ?>
                    <?php //= $form->field($model, 'fecha_nacimiento')->textInput() ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <?= $form->field($model, 'direccion')->textInput(['maxlength' => true]) ?>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <?= $form->field($model, 'telefono')->textInput(['maxlength' => true]) ?>
                </div>
            </div>
        </div>    

        <div class="row">
            <div class="col-md-4">
                <!-- DROP DOWN LIST PARA SELECCION DEL MUNICIPIO SEGUN EL MUNICIPIO --> 
                <div class="form-group">
                    <?= $form->field($model, 'id_cargo')->dropDownList(
                        ArrayHelper::map(Cargos::find()->all(), 'id', 'nombre'),
                        [
                            'class'=>'form-control',
                            'prompt'=>'[-- Seleccione Cargo --]',
                            'for'=>'disabledTextInput',
                            'id'=>'select-cargos'
                        ]
                    )?>
                </div>                
            </div>
            <div class="col-md-2" style="margin-top:25px">
                <?= Html::a('<span class="glyphicon glyphicon-plus-sign"></span> Cargo', ['cargos/create'], ['class'=>'btn btn-default']) ?>
                <!--<button class="btn btn-default"><span class="glyphicon glyphicon-plus-sign"></span> Cargo </button>-->
            </div>    


            <div class="col-md-4">
                <!-- DROP DOWN LIST PARA SELECCION DEL MUNICIPIO SEGUN EL MUNICIPIO --> 
                <div class="form-group">
                    <?= $form->field($model, 'id_estado')->dropDownList(
                        ArrayHelper::map(Estados::find()->where(['activo' => 1])->all(), 'id', 'nombre'),
                        [
                            'class'=>'form-control',
                            'prompt'=>'[-- Seleccione Estado --]',
                            'for'=>'disabledTextInput',
                            'id'=>'select-estados'
                        ]
                    )?>
                </div>                
            </div>
            <div class="col-md-2" style="margin-top:25px">
                <?= Html::a('<span class="glyphicon glyphicon-plus-sign"></span> Estado', ['estados/create'], ['class'=>'btn btn-default']) ?>
                <!--<button class="btn btn-default"><span class="glyphicon glyphicon-plus-sign"></span> Estado </button>-->
            </div>  
        </div>                    

        <?php //= $form->field($model, 'id_cargo')->textInput() ?>

        <?php //= $form->field($model, 'id_estado')->textInput() ?>

        <?php //= $form->field($model, 'fecha_registro')->textInput() ?>

        <div class="form-group">
            <?= Html::submitButton('Guardar Empleado', ['class' => 'btn btn-success']) ?>
        </div>
    
    </div>
    <?php ActiveForm::end(); ?>

</div>

views/empleados/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\EmpleadosSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="empleados-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'codigo') ?>

    <?= $form->field($model, 'lugar_nacimiento') ?>

    <?= $form->field($model, 'fecha_nacimiento') ?>

    <?= $form->field($model, 'direccion') ?>

    <?php // echo $form->field($model, 'telefono') ?>

    <?php // echo $form->field($model, 'id_cargo') ?>

    <?php // echo $form->field($model, 'id_estado') ?>

    <?php // echo $form->field($model, 'fecha_registro') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/empleados/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Empleados */

$this->title = 'Crear Empleados';
$this->params['breadcrumbs'][] = ['label' => 'Empleados', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="empleados-create col-md-8 col-md-offset-2">

    <h1><?= Html::encode($this->title) ?></h1>
    <hr/>
</div>

<div class="empleados-create">    
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/empleados/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\EmpleadosSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Empleados';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="empleados-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Crear Empleados', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'attribute' => 'codigo',
                'label' => 'Codigo',
                'value' => 'codigo',
                'contentOptions' => function($model){
                    return ['style' => 'width:100px' ];
                },
                'headerOptions' => ['class' => 'gridViewEmpleadosHeader'],
            ],
            'nombre',
            'lugar_nacimiento',
            //'fecha_nacimiento',
            [
                'attribute' => 'fecha_nacimiento',
                'label' => 'Fecha Nacimiento',
                'value' => function ($data) {
                    return substr($data->fecha_nacimiento,0,10); 
                },
                'contentOptions' => ['class' => 'gridViewEmpleados'],
                'headerOptions' => ['class' => 'gridViewEmpleadosHeader'],
            ],
            

            //'direccion',
            'telefono',
            //'id_cargo',
            [
                'attribute' => 'cargo_nombre',
                'label' => 'cargo',
                'value' => 'cargo.nombre',
                'contentOptions' => ['class' => 'gridViewEmpleados'],
                'headerOptions' => ['class' => 'gridViewEmpleadosHeader'],
            ],
            [
                'attribute' => 'estado_nombre',
                'label' => 'Estado',
                'value' => 'estado.nombre',
                'contentOptions' => function($model){
                    if($model->id_estado == 1){
                        return ['style' => 'color:#F39C12; font-weight:bold; '];
                    }

                    if($model->id_estado == 2){
                        return ['style' => 'color:#00A65A; font-weight:bold; '];
                    }

                    if($model->id_estado == 3){
                        return ['style' => 'color:#336699; font-weight:bold; '];
                    }

                    if($model->id_estado == 4){
                        return ['style' => 'color:#DD4B39; font-weight:bold; '];
                    }

                    if($model->id_estado == 5){
                        return ['style' => 'color:#7300D4; font-weight:bold; '];
                    }
                },
                'headerOptions' => ['class' => 'gridViewEmpleadosHeader'],
            ],
            [
                'attribute' => 'fecha_registro',
                'label' => 'Fecha Registro',
                'value' => function ($data) {
                    return substr($data->fecha_registro,0,10); 
                },
                'contentOptions' => ['class' => 'gridViewEmpleados'],
                'headerOptions' => ['class' => 'gridViewEmpleadosHeader'],
            ],

            ['class' => 'yii\grid\ActionColumn',
            'contentOptions' => function($model){
                return ['style' => 'width:100px' ];
            }],
        ],
    ]); ?>


</div>

views/empleados/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Empleados */

//$this->title = 'Update Empleados: ' . $model->id;
$this->title = "Datos del Empleado >> Agregar Datos";
$this->params['breadcrumbs'][] = ['label' => 'Empleados', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->nombre, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Actualizar Empleado';
?>
<div class="empleados-update col-md-8 col-md-offset-2">

    <h2><?= Html::encode($this->title) ?></h2>
    <hr/>
</div>

<div class="empleados-create">   
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/empleados/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Empleados */

$this->title = $model->nombre;
$this->params['breadcrumbs'][] = ['label' => 'Empleados', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="empleados-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Actualizar', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Eliminar', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Estas seguro de querer eliminar este item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <div class="col-md-6">
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'codigo',
            'nombre',
            'lugar_nacimiento',
            'fecha_nacimiento',
            'direccion',
            'telefono',
            'cargo.nombre',
            'estado.nombre',
            'fecha_registro',
        ],
    ]) ?>
    </div>

</div>